/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as AuthLogoutImport } from './routes/_auth/logout'
import { Route as AuthLoginTwitchImport } from './routes/_auth/login.twitch'
import { Route as AuthLoginCallbackImport } from './routes/_auth/login.callback'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLogoutRoute = AuthLogoutImport.update({
  id: '/_auth/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginTwitchRoute = AuthLoginTwitchImport.update({
  id: '/_auth/login/twitch',
  path: '/login/twitch',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginCallbackRoute = AuthLoginCallbackImport.update({
  id: '/_auth/login/callback',
  path: '/login/callback',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/_auth/logout': {
      id: '/_auth/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AuthLogoutImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login/callback': {
      id: '/_auth/login/callback'
      path: '/login/callback'
      fullPath: '/login/callback'
      preLoaderRoute: typeof AuthLoginCallbackImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login/twitch': {
      id: '/_auth/login/twitch'
      path: '/login/twitch'
      fullPath: '/login/twitch'
      preLoaderRoute: typeof AuthLoginTwitchImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/logout': typeof AuthLogoutRoute
  '/login/callback': typeof AuthLoginCallbackRoute
  '/login/twitch': typeof AuthLoginTwitchRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/logout': typeof AuthLogoutRoute
  '/login/callback': typeof AuthLoginCallbackRoute
  '/login/twitch': typeof AuthLoginTwitchRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/_auth/logout': typeof AuthLogoutRoute
  '/_auth/login/callback': typeof AuthLoginCallbackRoute
  '/_auth/login/twitch': typeof AuthLoginTwitchRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/logout' | '/login/callback' | '/login/twitch'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/logout' | '/login/callback' | '/login/twitch'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/_auth/logout'
    | '/_auth/login/callback'
    | '/_auth/login/twitch'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthLoginCallbackRoute: typeof AuthLoginCallbackRoute
  AuthLoginTwitchRoute: typeof AuthLoginTwitchRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthLoginCallbackRoute: AuthLoginCallbackRoute,
  AuthLoginTwitchRoute: AuthLoginTwitchRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/_auth/logout",
        "/_auth/login/callback",
        "/_auth/login/twitch"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/_auth/logout": {
      "filePath": "_auth/logout.tsx"
    },
    "/_auth/login/callback": {
      "filePath": "_auth/login.callback.tsx"
    },
    "/_auth/login/twitch": {
      "filePath": "_auth/login.twitch.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
